<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'release_calendar_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php 
            $year = "";
            $month = "";
            foreach ($_productCollection as $_product): 
                $release_month = date('n', strtotime($_product->getReleasedate()));
                $release_month_name = date('M', strtotime($_product->getReleasedate()));
                $release_year = date('Y', strtotime($_product->getReleasedate()));
                if(($month == "" && $year == "") || ($year<$release_year) || ($month<$release_month)){
                    echo "<li class='item product product-item label'>".$release_month_name." <span>".$release_year."</span></li>";
                  $month = $release_month;
                    $year = $release_year;
                }
            ?>
            <li class="item product product-item release-product">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image 
                        $imageId = 'product_base_image';
                        $_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
                         
                        $resizedImageUrl = $_imageHelper
                                                ->init($_product, $imageId)
                                                ->constrainOnly(true)
                                                ->keepAspectRatio(true)
                                                ->keepTransparency(true)
                                                ->keepFrame(false)
                                                ->resize($productImage->getWidth(), $productImage->getHeight())
                                                ->getUrl();

                    ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                       <span class="product-image-container product-image-container-<?php echo $_product->getId();?>">
                            <span class="product-image-wrapper">
                                <img class="product-image-photo" src="<?php echo $resizedImageUrl;?>" width="<?php echo $productImage->getWidth();?>" height="<?php echo $productImage->getHeight();?>" alt="<?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>"/>
                            </span>
                        </span>
                        <?php //echo $productImage->toHtml() ?>
                        
                    </a>


                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
                        <div class="product-item-inner">
                            <div class="product attributes-data">
                                <p><?= $escaper->escapeHtml(__('Release Date')) ?></p>
                                <?php $release_date = date('Y-m-d', strtotime($_product->getReleasedate())); ?>
                                <p class="date"><?= $release_date; ?></p>
                            </div>
                            <div class="product description product-item-description">
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                   title="<?= /* @noEscape */ $_productNameStripped ?>"
                                   class="action more primary"><?= $escaper->escapeHtml(__('See More')) ?></a>
                            </div>
                            
                        </div>
                    </div>
                </div>
                <?= strpos($pos, $viewMode . '-actions') ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
