<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<style type="text/css">
    .modal-popup .modal-inner-wrap{ width: 50%; }
</style>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<?php $viewModel = $block->getData('viewModel'); 
         if($viewModel->isCustomerLoggedIn()){
            $regHref = $block->escapeUrl($block->getSignupUrl());
         }else{
            $regHref = "#";
         }
   ?>
<div class="product alert <?= $block->getHtmlClass() ?>"> 
   
    <a href="<?php echo $regHref; ?>" id="alertTest"
       title="<?= $block->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert">
        <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
    </a>
</div>

<?php if(!$viewModel->isCustomerLoggedIn()){ ?>
<div id="popup-modal" style="display:none;">
    <p>Please register to get notification when product is back in-stock.</p>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Order Review',
                width: 200,
                height: 300,
                buttons: [{
                    text: $.mage.__('Cancel'),
                    class: '',
                    click: function () {   
                        this.closeModal();
                    }
                },
                {
                    text: $.mage.__('Ok'),
                    class: '',
                    click: function () {
                        
                        window.location.href = "<?= $block->getUrl('customer/account/create/') ?>";
                        //this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#alertTest").on('click',function(){ 
                $("#popup-modal").modal("openModal");
            });

        }
    );
</script>
<?php } ?>