<?php
// @codingStandardsIgnoreFile
?>
<?php if ($arpBlocks = $block->getBlocks()) : ?>
    <?php foreach ($arpBlocks as $arpBlock) : ?>
        <div
            data-aw-arp-block-rule-id="<?= /* @noEscape */ $block->getRuleIdForBlock($arpBlock) ?>"
            data-mage-init='<?= /* @noEscape */ $block->getDataMageInitForBlock($arpBlock) ?>'
            class="aw-arp-container <?= /* @noEscape */ $block->getAdditionalCssClassesForBlock($arpBlock) ?>"
            style="margin-bottom: 35px; opacity: 1 !important;">
            <h3 class="aw-arp-container__title" style="font-weight: bold; margin-top: 0;">
                <?= $block->escapeHtml($arpBlock->getRule()->getTitle()) ?>
            </h3>
            <div
                data-aw-arp-block="items"
                class="aw-arp-container__items"
                style="overflow: hidden; margin: 0 -10px -20px;">
                <?php foreach ($arpBlock->getProducts() as $product) : ?>
                    <?php if ($product === null) : ?>
                        <?php continue; ?>
                    <?php endif ?>
                    <div
                        data-aw-arp-block="item"
                        class="aw-arp-container__item"
                        style="
                            box-sizing: border-box;
                            padding: 0 10px;
                            text-align: center;
                            float: left;
                            margin-bottom: 20px;">
                        <div class="product-item" style="padding-left: 0 !important;">
                            <div class="product-item-info" style="width: auto;">
                                <?php $productUrl = $block->getProductUrl($product) ?>
                                <a href="<?= /* @noEscape */ $productUrl ?>"
                                   class="product-item-photo">
                                        <span class="product-image-container">
                                            <span class="product-image-wrapper" style="height: auto;">
                                                <img class="product-image-photo"
                                                     src="<?= /* @noEscape */ $block
                                                         ->getImage($product, 'product_base_image')
                                                         ->getImageUrl(); ?>"
                                                     width="240" 
                                                     height="300" 
                                                     alt="<?= $block->escapeHtml($product->getName()) ?>"
                                                     style="position: static;">
                                            </span>
                                        </span>
                                </a>

                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtml($product->getName()) ?>"
                                           href="<?= /* @noEscape */ $productUrl ?>"
                                           class="product-item-link"><?= $block->escapeHtml($product->getName()) ?></a>
                                    </strong>

                                    <div class="price-box">
                                        <?= /* @noEscape */ $product->getFormattedPrice(); ?>
                                    </div>
                                    <div class="actions-primary">
                                        <?php if ($product->getIsSalable()) : ?>
                                            <div class="stock assvailable">
                                                <span><?= /* @noEscape */ __('In stock') ?></span>
                                            </div>
                                        <?php else : ?>
                                            <div class="stock unavailable">
                                                <span><?= /* @noEscape */ __('Out of stock') ?></span>
                                            </div>
                                        <?php endif ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    <?php endforeach ?>
<?php endif ?>